# Numpy
 + Numpy is a general purpose array processing package
 + It is open source library.
 + In python we have lists that serves the purpose of arrays, but they are slow to process
 + Numpy aims to provide an array object that is up to 50% faster than traditional python list

In [1]:
#!pip install numpy

In [2]:
import numpy as np

In [3]:
#Array creation

In [4]:
a = np.array([1,2,3,4,5])
print (a)
type(a)
a.ndim

[1 2 3 4 5]


1

In [5]:
#Zero dimensional array


In [6]:
z = np.array(10)

In [7]:
a = np.array([1,2,3,4,5])
a.ndim

1

In [8]:
t = np.array([[1,2,3,4,5]]) #If bracket is two then it is 2dimensional, if it 3 bracket then it is 3 dim
t.ndim

2

In [9]:
b = np.array([[[1,2,3,4,5]]])
print(b)
print(b.ndim)

[[[1 2 3 4 5]]]
3


In [10]:
#Change data type

In [11]:
a = np.array([[1,2,3,4]], dtype = 'float')
a

array([[1., 2., 3., 4.]])

In [12]:
a = np.array([[1,2,3,4]], dtype = 'str')
a

array([['1', '2', '3', '4']], dtype='<U1')

### Other ways of creating an array
1. arange
2. linspace
3. zeros
3. ones
4. Random

In [13]:
a = np.arange(10,20)

In [14]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
b = np.linspace(1, 20, 25) # Values is to be evenly spaced

In [16]:
b

array([ 1.        ,  1.79166667,  2.58333333,  3.375     ,  4.16666667,
        4.95833333,  5.75      ,  6.54166667,  7.33333333,  8.125     ,
        8.91666667,  9.70833333, 10.5       , 11.29166667, 12.08333333,
       12.875     , 13.66666667, 14.45833333, 15.25      , 16.04166667,
       16.83333333, 17.625     , 18.41666667, 19.20833333, 20.        ])

In [17]:
c = np.linspace(1, 20, 25, retstep= True)

In [18]:
c

(array([ 1.        ,  1.79166667,  2.58333333,  3.375     ,  4.16666667,
         4.95833333,  5.75      ,  6.54166667,  7.33333333,  8.125     ,
         8.91666667,  9.70833333, 10.5       , 11.29166667, 12.08333333,
        12.875     , 13.66666667, 14.45833333, 15.25      , 16.04166667,
        16.83333333, 17.625     , 18.41666667, 19.20833333, 20.        ]),
 0.7916666666666666)

In [19]:
d = np.zeros([2,4])
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
m = np.zeros([2,2])
m

array([[0., 0.],
       [0., 0.]])

In [21]:
o = np.ones([2,4])
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
r = np.random.rand(2,4)
r

array([[0.82500521, 0.4157627 , 0.59920048, 0.32600519],
       [0.29614506, 0.89441827, 0.74218964, 0.84397477]])

In [42]:
r = np.random.randint(2,10,10)
r

array([6, 3, 5, 6, 3, 4, 7, 9, 7, 7])

### Slicing and indexing of arrays

In [27]:
a = np.array([[1,2,3],[7,8,9]])

In [28]:
a

array([[1, 2, 3],
       [7, 8, 9]])

In [29]:
a [0,0]    #[row,col]

1

In [30]:
a [1,2]            

9

In [31]:
a[:,1:]

array([[2, 3],
       [8, 9]])

In [32]:
a [0,1:]

array([2, 3])

In [38]:
a [0,0:2]

array([1, 2])

In [33]:
a [1,1:]

array([8, 9])

In [34]:
a

array([[1, 2, 3],
       [7, 8, 9]])

In [37]:
# 1 & 9
a [[0,1], [0,2]]

array([1, 9])

# Reshaping the arrays

In [44]:
x = np.random.rand(2,4)
x

array([[0.27201275, 0.60077727, 0.18034439, 0.19090852],
       [0.79602383, 0.47300159, 0.31979622, 0.07360361]])

In [45]:
x.reshape(1,8)

array([[0.27201275, 0.60077727, 0.18034439, 0.19090852, 0.79602383,
        0.47300159, 0.31979622, 0.07360361]])

In [46]:
x.reshape(4,2)

array([[0.27201275, 0.60077727],
       [0.18034439, 0.19090852],
       [0.79602383, 0.47300159],
       [0.31979622, 0.07360361]])

### Aggregate fun

In [67]:
a = np.array([1,2,3,4,5])

In [68]:
a.sum()

15

In [69]:
a.min()

1

In [70]:
a.max()

5

In [71]:
a.std()

1.4142135623730951

In [72]:
a.mean()

3.0

### Stacking

+ It is uded to join 3 different arrays
+ vertical and horizontal array

In [73]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [74]:
c = np.vstack([a,b])

In [75]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
d = np.hstack([a,b])

In [78]:
d

array([1, 2, 3, 4, 5, 6])